#CAPTCHA, lockout, rate-limiting, TOTP, pepper

attack:
  bruteforce:
  passwordspraying:
config:
  hash:
  pass_level:
  salt: 
  pepper:
protection:
  captcha: false
  lockout: false
  rate-limit: false
  TOTP: false
GROUP_SEED: 114467408
  